[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
recur = "Dtzj1BPFspDjfACbQXDZ1Hsx6CizeYRg9aa2Po1BAawA"

[programs.devnet]
recur = "Dtzj1BPFspDjfACbQXDZ1Hsx6CizeYRg9aa2Po1BAawA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --import tsx --test tests/*.test.ts"
