[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
recur = "5q4Mnn9HuUfhMjh74xadC19Sh1dZAfjkRHJsJDZZhsW8"

[programs.devnet]
recur = "5q4Mnn9HuUfhMjh74xadC19Sh1dZAfjkRHJsJDZZhsW8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --import tsx --test tests/*.test.ts"
